services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/tedecom
      - LOG_DIR=/var/log/tedecom
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
